//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topdesk_Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class changeactivity
    {
        public string action { get; set; }
        public Nullable<System.Guid> activitytemplateid { get; set; }
        public bool approved { get; set; }
        public Nullable<System.DateTime> approveddate { get; set; }
        public Nullable<System.Guid> archivereasonid { get; set; }
        public string briefdescription { get; set; }
        public Nullable<System.Guid> categoryid { get; set; }
        public System.Guid changeid { get; set; }
        public string comments { get; set; }
        public decimal currentplanexpenses { get; set; }
        public long currentplantimetaken { get; set; }
        public Nullable<System.DateTime> dataanmk { get; set; }
        public Nullable<System.DateTime> datwijzig { get; set; }
        public int decidedby { get; set; }
        public Nullable<System.Guid> decidedbypersonid { get; set; }
        public decimal expectedexpenses { get; set; }
        public long expectedtimetaken { get; set; }
        public decimal expenses { get; set; }
        public Nullable<System.Guid> groupid { get; set; }
        public int importtype { get; set; }
        public Nullable<System.Guid> milestoneid { get; set; }
        public string number { get; set; }
        public Nullable<System.Guid> operatorgroupid { get; set; }
        public Nullable<System.Guid> operatorid { get; set; }
        public decimal originalplanexpenses { get; set; }
        public long originalplantimetaken { get; set; }
        public int changephase { get; set; }
        public Nullable<System.DateTime> plannedfinaldate { get; set; }
        public Nullable<System.DateTime> plannedstartdate { get; set; }
        public int planningfixed { get; set; }
        public decimal realizedexpenses { get; set; }
        public bool rejected { get; set; }
        public Nullable<System.DateTime> rejecteddate { get; set; }
        public Nullable<System.Guid> rejectionreasonid { get; set; }
        public string description { get; set; }
        public bool resolved { get; set; }
        public Nullable<System.DateTime> resolveddate { get; set; }
        public bool skipped { get; set; }
        public Nullable<System.DateTime> skippeddate { get; set; }
        public Nullable<System.Guid> skippedreasonid { get; set; }
        public bool started { get; set; }
        public Nullable<System.DateTime> starteddate { get; set; }
        public int status { get; set; }
        public Nullable<System.Guid> subcategoryid { get; set; }
        public long timetaken { get; set; }
        public Nullable<System.Guid> uidaanmk { get; set; }
        public Nullable<System.Guid> uidwijzig { get; set; }
        public System.Guid unid { get; set; }
        public Nullable<System.DateTime> vrijedatum1 { get; set; }
        public double vrijegetal1 { get; set; }
        public bool vrijelogisch1 { get; set; }
        public string vrijememo1 { get; set; }
        public Nullable<System.Guid> vrijeopzoek1 { get; set; }
        public string vrijetekst1 { get; set; }
        public Nullable<System.DateTime> vrijedatum2 { get; set; }
        public double vrijegetal2 { get; set; }
        public bool vrijelogisch2 { get; set; }
        public string vrijememo2 { get; set; }
        public Nullable<System.Guid> vrijeopzoek2 { get; set; }
        public string vrijetekst2 { get; set; }
        public Nullable<System.DateTime> vrijedatum3 { get; set; }
        public double vrijegetal3 { get; set; }
        public bool vrijelogisch3 { get; set; }
        public string vrijememo3 { get; set; }
        public Nullable<System.Guid> vrijeopzoek3 { get; set; }
        public string vrijetekst3 { get; set; }
        public Nullable<System.DateTime> vrijedatum4 { get; set; }
        public double vrijegetal4 { get; set; }
        public bool vrijelogisch4 { get; set; }
        public string vrijememo4 { get; set; }
        public Nullable<System.Guid> vrijeopzoek4 { get; set; }
        public string vrijetekst4 { get; set; }
        public Nullable<System.DateTime> vrijedatum5 { get; set; }
        public double vrijegetal5 { get; set; }
        public bool vrijelogisch5 { get; set; }
        public string vrijememo5 { get; set; }
        public Nullable<System.Guid> vrijeopzoek5 { get; set; }
        public string vrijetekst5 { get; set; }
        public Nullable<System.DateTime> attvrijedatum1 { get; set; }
        public double attvrijegetal1 { get; set; }
        public bool attvrijelogisch1 { get; set; }
        public string attvrijememo1 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek1 { get; set; }
        public string attvrijetekst1 { get; set; }
        public Nullable<System.DateTime> attvrijedatum2 { get; set; }
        public double attvrijegetal2 { get; set; }
        public bool attvrijelogisch2 { get; set; }
        public string attvrijememo2 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek2 { get; set; }
        public string attvrijetekst2 { get; set; }
        public Nullable<System.DateTime> attvrijedatum3 { get; set; }
        public double attvrijegetal3 { get; set; }
        public bool attvrijelogisch3 { get; set; }
        public string attvrijememo3 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek3 { get; set; }
        public string attvrijetekst3 { get; set; }
        public Nullable<System.DateTime> attvrijedatum4 { get; set; }
        public double attvrijegetal4 { get; set; }
        public bool attvrijelogisch4 { get; set; }
        public string attvrijememo4 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek4 { get; set; }
        public string attvrijetekst4 { get; set; }
        public Nullable<System.DateTime> attvrijedatum5 { get; set; }
        public double attvrijegetal5 { get; set; }
        public bool attvrijelogisch5 { get; set; }
        public string attvrijememo5 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek5 { get; set; }
        public string attvrijetekst5 { get; set; }
        public long duration_in_workdays { get; set; }
        public long duration_in_minutes { get; set; }
        public string bespokememo { get; set; }
        public Nullable<System.Guid> activitystatusid { get; set; }
        public bool maystart { get; set; }
        public string importid { get; set; }
        public Nullable<System.DateTime> importdate { get; set; }
        public bool monitored { get; set; }
        public string ref_operator_name { get; set; }
        public string ref_change_brief_description { get; set; }
        public string ref_change_number { get; set; }
        public Nullable<System.Guid> appointmentid { get; set; }
        public bool displayincalendar { get; set; }
    
        public virtual change change { get; set; }
    }
}
