//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topdesk_Dashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class topdesk5Entities : DbContext
    {
        public topdesk5Entities()
            : base("name=topdesk5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<change> changes { get; set; }
        public DbSet<incident> incidents { get; set; }
        public DbSet<changeactivity> changeactivities { get; set; }
    }
}
